// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxpryqfdmmiemvbhyjwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4cHJ5cWZkbW1pZW12Ymh5andmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MTc3MDcsImV4cCI6MjA2NDM5MzcwN30.ACSOCPGORLJnu7rMpwQTWMZfcmcZZYJsupDSwG2l6uY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);